apiVersion: apps/v1

kind: Deployment
metadata:
  name: goal-tracker
  namespace: goaltracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goal-tracker
  template:
    metadata:
      labels:
        app: goal-tracker
    spec:
      nodeSelector:
        tier: goaltrackerv1
      containers:
        - name: api
          image: goaltracker-app:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
          env:
            # 1. THE NUCLEAR OPTION: Disables the entire OTel SDK at the root
            - name: OTEL_SDK_DISABLED
              value: "true"
            # 2. Specifically kills the metrics and trace exporters
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            # 3. Tells Spring Boot/Micrometer to stop pushing to OTLP
            - name: MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED
              value: "false"
            - name: MANAGEMENT_OTLP_TRACING_EXPORT_ENABLED
              value: "false"

